### ISSUE TITLE
educationRequirements in JobPosting missing

### ISSUE THREAD

**Issue by kimchristiansen** [brotkrueml/schema#39]
First of all thanks alot for the awesome extension!

educationRequirements (https://schema.org/educationRequirements) is missing in JobPosting (https://schema.org/JobPosting).
Is the missing attribute added automatically after the schema.org terms update (https://github.com/brotkrueml/schema/issues/3) ?

**Comment by brotkrueml** [comment]
Thanks for the compliment :-)

"educationRequirement" is currently a pending property (recognisable by the blue colour). I don't add pending properties (or types) to the schema definition because they can change or vanish again - which would introduce unwanted breaking changes. When they are moved to the official specification (brown colour) they are added with the next update.

With the upcoming schema version 1.6 you have the possibility to use a slot or PSR-14 event listener to register additional properties to existing types, see #36 and have a look at the documentation:
https://docs.typo3.org/p/brotkrueml/schema/master/en-us/Developer/Events.html#register-additional-properties-for-a-type

I use in the schema extension a slot/event listener to add properties moved from official to pending (because of reasons) and to avoid BC:
https://github.com/brotkrueml/schema/blob/master/Classes/EventListener/RegisterTypePropertiesMovedFromOfficialToPending.php

I don't know yet when to release version 1.6, I want to have additional features in it. But you can give the master branch or 1.6.x-dev branch alias a try. Feedback is welcome :-)

**Comment by kimchristiansen** [comment]
Thanks for the fast answer!
seeing forward fo version 1.6
