### ISSUE TITLE
Adding Event.eventAttendanceMode property

### ISSUE THREAD

**Issue by ohader** [brotkrueml/schema#93]
> [...] optional properties: [organizer](https://developers.google.com/search/docs/advanced/structured-data/event#organizer), [eventStatus](https://developers.google.com/search/docs/advanced/structured-data/event#eventstatus), [eventAttendanceMode](https://developers.google.com/search/docs/advanced/structured-data/event#event-attendance-mode), and [previousStartDate](https://developers.google.com/search/docs/advanced/structured-data/event#previous-start-date)

see https://developers.google.com/search/docs/advanced/structured-data/event#event-attendance-mode
see https://schema.org/EventAttendanceModeEnumeration

```json
{
"@context": "https://schema.org",
"@type": "Event",
"eventAttendanceMode": "https://schema.org/OnlineEventAttendanceMode",
"location": {
  "@type":"VirtualLocation",
  "url": "https://operaonline.stream5.com/"
  }
}
```

**Comment by brotkrueml** [comment]
The property `eventAttendanceMode` is a pending property:
https://schema.org/docs/pending.home.html

The schema extension delivers only types and properties from the core vocabulary. It does not deliver pending types and properties to avoid breaking changes when updating the vocabulary (which also means the schema extension must then release a new major release instead of a feature release). You have now two possibilities:
- Install the [schema_pending](https://extensions.typo3.org/extension/schema_pending) extension (which provides all pending types and properties, which are a lot)
- Register the necessary property with a PSR-14 event: https://docs.typo3.org/p/brotkrueml/schema/2.4/en-us/Developer/Events.html#event-register-additional-properties

I suggest the PSR-14 event, this way you have the control and add only those pending properties which are really needed. Once a pending property is moved to the core vocabulary, a property added with a PSR-14 event does not harm.

Also have a look at the documentation about the different schema.org vocabularies:
https://docs.typo3.org/p/brotkrueml/schema/2.4/en-us/Introduction/Index.html#the-schema-org-vocabulary

**Comment by brotkrueml** [comment]
FYI: I opened a request on schema.org to move the pending types and properties for events (that are suggested by Google since two years) to the core vocabulary:
https://github.com/schemaorg/schemaorg/issues/3110
